name: Run Command on Remote Server and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Clone Storage Repository
      run: |
        git clone https://github.com/Amk-001/-0.git /path/to/storage

    - name: Run Remote Command
      run: |
        ssh -o StrictHostKeyChecking=no mynetwork@192.168.1.11 << 'EOF'
          cd /path/to/your/application  # Navigate to application directory
          git pull origin main  # Pull latest code
          sudo systemctl restart apache2  # Restart Apache server (or change to nginx if needed)
        EOF

    - name: Test Website Deployment
      run: |
        curl -I http://192.168.1.11:8080  # Test if the website is running
