name: Deploy to Remote Server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Set Up SSH Key
    - name: Set Up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Deploy Code to Server
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no mynetwork@192.168.1.11 << 'EOF'
          # Navigate to web root
          cd /var/www/html

          # Backup existing files (optional)
          if [ ! -d backup ]; then
            mkdir backup
          fi
          cp -r . backup/$(date +'%Y%m%d%H%M%S')/

          # Pull the latest code from GitHub
          git init
          git remote add origin git@github.com:yourusername/your-repository.git
          git fetch --all
          git reset --hard origin/main

          # Restart the web server (if applicable)
          sudo systemctl restart apache2
        EOF
