name: Deploy to Remote Server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code from Repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Set Up SSH Access
    - name: Set Up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # Step 3: Deploy Code to Remote Server
    - name: Deploy to Server
      run: |
        sshpass -p "449530" ssh -o StrictHostKeyChecking=no mynetwork@192.168.1.11 << 'EOF'
          # Step 3.1: Navigate to Web Root Directory
          cd /var/www/html

          # Step 3.2: Backup Existing Files
          if [ ! -d backup ]; then
            mkdir backup
          fi
          cp -r . backup/$(date +'%Y%m%d%H%M%S')/

          # Step 3.3: Clone Storage Repository
          git clone https://github.com/Amk-001/-0.git temp_repo
          cp -r temp_repo/* .
          rm -rf temp_repo

          # Step 3.4: Restart Web Server
          sudo systemctl restart apache2
        EOF

    # Step 4: Test Website Deployment
    - name: Test Website Deployment
      run: |
        curl -I http://192.168.1.11:8080
